on: 
  push:
   branches:
      - main
      
name: deploy website on push
jobs:
  web-deploy:
     name: Deploy
     runs-on: ubuntu-latest
     steps:
     - name: Get latest code
       uses: actions/checkout@v2.3.2

       env:
        FTP_SERVER: ${{ secrets.FTP_SERVER }}
        FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
       with:
         server: ftp.netelmart.net
         username: dev@dev.netelmart.net
         password: JlSf]ePibW[p
         server-dir: /dev.netelmart.net/

  
